update scripts since time alloted

diff --git a/src/usr/local/bin/app-updater b/src/usr/local/bin/app-updater
--- a/src/usr/local/bin/app-updater
+++ b/src/usr/local/bin/app-updater
@@ -1,29 +1,155 @@
 #!/bin/bash
-set -ex;
     
-APP_NAME=${1:-none};
-UPDATE_PATH=${2:-none};
-CATALINA_HOME=${CATALINA_HOME:-none};
+show_help()
+{
+   echo "Deploy/Update Application";
+   echo
+   echo "Syntax: "
+   echo     "Apache: app-updater -a -n 'myapp' -p '/opt/updates'";
+   echo     "Tomcat: app-updater -t -n 'myapp' -p '/opt/updates'";
+   echo
+   echo "Required:";
+   echo "a|t  Use -a for apache, -t for tomcat"
+   echo "n    Name of the app, e.g myapp.war would be myapp, or for html app, name would be the folder name in update path";
+   echo "p    Path to where the app is located, without the trailing slash, e.g /opt/updates";
+   echo
+   echo "Options:";
+   echo "h    Print Help";
+   echo "f    Fail if updates not found when deployment exists, default: FALSE";
+   echo "x    Disable auto-update";
+   echo
+}
     
-if [[ "${CATALINA_HOME}" != "none" ]];then
-    APP_LOCAL="";
-    APP_PATH="${UPDATE_PATH}/${APP_NAME}.war";
-    DEPLOY_PATH="${CATALINA_HOME}/webapps";
-    if [ -f "${CATALINA_HOME}/webapps/${APP_NAME}.war" ];then
-        APP_LOCAL=$(sha1sum "${DEPLOY_PATH}/${APP_NAME}.war" | awk '{print $1}');
-        echo "App Updater: Application exists, sha1: ${APP_LOCAL}";
-    else 
-        echo "App Updater: Application DOES NOT exist and will be deployed from: ${APP_PATH}";
-    fi
-    if [ -f "${APP_PATH}" ]; then
-        APP_LATEST=$(sha1sum ${APP_PATH} | awk '{print $1}');
-        if [ "${APP_LOCAL}" != "${APP_LATEST}" ];then
-            echo "App Updater: Update is needed, using update path: ${APP_PATH}";
-            cp ${APP_PATH} ${DEPLOY_PATH};
-        else
-            echo "App Updater: Update is not needed";
-        fi;
-    else 
-        echo "App Updater: Application not found at ${APP_PATH}";
+get_signature()
+{
+    option="$1";
+    object="$2";
+    if [ -d "${object}" ];then
+        set_metadata "${option}" "${object}";
+        echo "$(sha1sum ${APP_CACHE}/${APP_NAME}.${option}.metadata | awk '{print $1}')";
+    elif [ -f "${option}" ];then
+        echo "$(sha1sum ${object} | awk '{print $1}')";
+    else
+        echo "0";
     fi;
+}
+    
+set_metadata()
+{
+    option="$1";
+    object="$2";
+    if [ -f "${APP_CACHE}/${APP_NAME}.${option}.metadata" ];then
+        rm "${APP_CACHE}/${APP_NAME}.${option}.metadata";
+    fi;
+    (cd "${object}";
+        for i in *; do 
+            sha1sum "$i"; 
+    done) >> "${APP_CACHE}/${APP_NAME}.${option}.metadata";
+    cd /opt;
+}
+    
+deploy_app()
+{
+    if [ -d "${APP_LATEST}" ];then
+        cp -R ${APP_LATEST}/* ${APP_BASE};
+    else
+        cp -R ${APP_LATEST} ${APP_BASE};
+    fi;
+}
+    
+update_app()
+{
+    if [ "${SIG_LOCAL}" == "${SIG_UPDATE}" ];then
+        echo "App Updater: Update is not needed, deployed: ${SIG_LOCAL}, latest: ${SIG_UPDATE}";
+        exit 0;
+    fi;
+    if [ "${UPDATE_AUTO}" == "TRUE" ];then
+        deploy_app;
+    fi;
+}
+    
+#Static
+APP_CACHE="/var/cache";
+CATALINA_HOME="${CATALINA_HOME:-}";
+BASE_HTML="/var/www/html";
+BASE_TOMCAT="${CATALINA_HOME}/webapps";
+    
+#Dynamic
+APP_BASE="";
+APP_NAME="";
+APP_TYPE="";
+UPDATE_PATH="";
+UPDATE_AUTO="TRUE";
+UPDATE_FAIL="FALSE";
+    
+#Run
+while getopts ":afhtxn:p:" option; do
+    case $option in
+      h)
+        show_help
+        exit;;
+      n)
+        APP_NAME=$OPTARG;;
+      p)
+        UPDATE_PATH=$OPTARG;;
+      f)
+        UPDATE_FAIL="TRUE";;
+      x)
+        UPDATE_AUTO="FALSE";;
+      a)
+        APP_BASE="${BASE_HTML}"
+        APP_TYPE="apache";;
+      t)
+        APP_BASE="${BASE_TOMCAT}/"
+        APP_TYPE="tomcat";;
+      \?)
+        echo "Error: Invalid option, -h for help"
+        exit;;
+    esac
+done
+    
+if [ "${APP_TYPE}" == "" ];then
+    echo "App Updater: Required App Type is not set, use -a for apache or -t for tomcat, -h for help";
+    exit 22;
+fi;
+if [ "${APP_TYPE}" == "tomcat" ] && [ "${CATALINA_HOME}" == "" ];then
+    echo "App Updater: CATALINA_HOME is undefined";
+    exit 5;
+fi;
+if [ "${APP_NAME}" == "" ];then
+    echo "App Updater: Required App Name is not set, use -n to set the name, -h for help";
+    exit 22;
+fi;
+if [ "${UPDATE_PATH}" == "" ];then
+    echo "App Updater: Required App Path is not set, use -p to set the path to application, -h for help";
+    exit 22;
+fi;
+if [ "${APP_TYPE}" == "apache" ];then
+    APP_DEPLOY="${BASE_HTML}";
+    APP_LATEST="${UPDATE_PATH}/${APP_NAME}/";
+elif [ "${APP_TYPE}" == "tomcat" ];then
+    APP_DEPLOY="${BASE_TOMCAT}/${APP_NAME}.war";
+    APP_LATEST="${UPDATE_PATH}/${APP_NAME}.war";
+else
+    echo "Unknown application type";
+    exit 5;
+fi;
+
+SIG_LOCAL=$(get_signature "local" "${APP_DEPLOY}");
+SIG_UPDATE=$(get_signature "update" "${APP_LATEST}");
+
+if [ "${SIG_LOCAL}" == "0" ] && [ "${SIG_UPDATE}" == "0" ];then
+    echo "App Updater: Application has not been deployed and was not found in ${UPDATE_PATH}";
+    exit 2;
+elif [ "${SIG_LOCAL}" == "0" ] && [ "${SIG_UPDATE}" != "0" ];then
+    echo "App Updater: Application has not been deployed, deploying from ${UPDATE_PATH}";
+    deploy_app;
+elif [ "${SIG_LOCAL}" != "0" ] && [ "${SIG_UPDATE}" == "0" ];then
+    echo "App Updater: Application is deployed but update is empty, failure enabled: ${UPDATE_FAIL}";
+    if [ "${UPDATE_FAIL}" == "TRUE" ];then
+        exit 2;
+    fi;
+else
+    echo "App Updater: Auto-update is enabled: ${UPDATE_AUTO}, deployed: ${SIG_LOCAL}, latest: ${SIG_UPDATE}";
+    update_app;
 fi;
diff --git a/src/usr/local/bin/cert-updater b/src/usr/local/bin/cert-updater
--- a/src/usr/local/bin/cert-updater
+++ b/src/usr/local/bin/cert-updater
@@ -1,60 +1,144 @@
 #!/bin/bash
-set -ex;
-    
 ############
+set -eux;
+show_help()
+{
+   echo "Update CA Trust Stores";
+   echo
+   echo "Syntax: cert-updater [-h|a|o|j|k|f] [-p|c]";
+   echo
+   echo "Default:";
+   echo "    Auto-update all stores and generate new keypair if needed";
+   echo "    Filter: *_CA.crt";
+   echo
+   echo "Options:";
+   echo "h    Print Help";
+   echo "a    Auto-update, update OS, and if JAVA_HOME deetected update cacerts, generates new key if default keys found";
+   echo "o    Update OS Certificate Store";
+   echo "j    Update Java Certificate Store";
+   echo "k    Generate new server certificate and key";
+   echo "p    Path or URL to where the CA Certs are to add, you can use -f option to filter";
+   echo "f    Filter for CA cert import, default: *_CA.crt";
+   echo "c    Subject name for new localhost certificate and key";
+   echo
+}
     
-URL=${1:-none};
-SUBJECT=${2:-localhost};
+URL="";
+SUBJECT="localhost";
 JAVA_HOME=${JAVA_HOME:-none};
+UPDATE="AUTO";
+FILTER="*_CA.crt";
     
-## Keygen ##
-echo "Keygen: Checking for certificate generation";
+function auto_update()
+{
+   update_keys;
+   update_os;
+   update_jvm;
+   cleanup;
+}
     
-if [[ -f "/etc/ssl/default.keys" ]]; then
-    echo "Keygen: Default build keys detected, new pair will be generated";
-    openssl dhparam -out /etc/ssl/dhparams.pem 2048;
-    openssl req -newkey rsa:2048 -x509 -nodes -keyout /etc/ssl/server.key -new -out /etc/ssl/server.pem -subj /CN=${SUBJECT} -sha256 -days 3650;
-    rm /etc/ssl/default.keys;
-fi
+function update_keys()
+{
+    if [ -f "/etc/ssl/default.keys" ];then
+        rm /etc/ssl/default.keys;
+        openssl dhparam -out /etc/ssl/dhparams.pem 3072;
+        openssl req -newkey rsa:2048 -x509 -nodes -keyout /etc/ssl/server.key -new -out /etc/ssl/server.pem -subj /CN=${SUBJECT} -sha256 -days 3650;
+        PEM_SHA1=$(openssl x509 -noout -fingerprint -sha1 -in /etc/ssl/server.pem | cut -f2 -d"=" | sed "s/://g" | awk '{print tolower($0)}');
+        echo "Cert Updater: Keygen finished, Thumbprint: $PEM_SHA1";
+    fi;
+}
     
-PEM_SHA1=$(openssl x509 -noout -fingerprint -sha1 -in /etc/ssl/server.pem | cut -f2 -d"=" | sed "s/://g" | awk '{print tolower($0)}');
-echo "Keygen: Finished, Certificate Thumbprint: $PEM_SHA1";
+function update_jvm()
+{
+    get_certs;
+    if [ "${JAVA_HOME}" != "none" ];then
+        for CA_CRT in /usr/local/share/ca-certificates/*.crt; do
+            CA_NAME=$(openssl x509 -noout -subject -nameopt multiline -in $CA_CRT | sed -n 's/ *commonName *= //p');
+            CA_EXISTS=$(${JAVA_HOME}/bin/keytool -list -cacerts -storepass changeit -alias "$CA_NAME" | echo $?);
+            if [ "$CA_EXISTS" -eq 0 ];then
+                ${JAVA_HOME}/bin/keytool -import -trustcacerts -cacerts \
+                    -storepass changeit -noprompt -alias "$CA_NAME" -file $CA_CRT >/dev/null 2>&1 \
+                    | echo "Cert Updater: Added certificate to cacert, $CA_CRT";
+            else 
+                echo "Cert Updater: Certificate ${CA_NAME} already exists, not adding";
+            fi;
+        done;
+    else 
+        echo "Cert Updater: JAVA_HOME is undefined in environment, nothing to import";
+    fi;
+    if [ "${UPDATE}" != "AUTO" ];then
+        cleanup;
+    fi;
+}
     
-## CA Certificates ##
-echo "CA Certificates: Checking for CA Import";
-if [[ "${URL}" != "none" ]];then
-    IS_URL='^(http|https)';
-    echo "CA Certificates: The following location will be searched ${URL}";
-    cd /usr/local/share/ca-certificates;
-    if [[ ${URL} =~ ${IS_URL} ]];then
-        wget -r -nH -A *_CA.crt ${URL};
-    else
-        if [[ ! -d ${URL} ]];then
-            echo "CA Certificates: ${URL} does not exist, nothing to import";
-        else 
-            cp -R ${URL} /usr/local/share/ca-certificates/;
-        fi
-    fi
-    HAS_CRTS=$(ls /usr/local/share/ca-certificates/*.crt 2> /dev/null | wc -l);
-    if [[ "${HAS_CRTS}" -ne 0 ]];then
-        if [[ "${JAVA_HOME}" != "none" ]];then
-            for CA_CRT in /usr/local/share/ca-certificates/*.crt; do
-                CA_NAME=$(openssl x509 -noout -subject -nameopt multiline -in $CA_CRT | sed -n 's/ *commonName *= //p');
-                CA_EXISTS=$(${JAVA_HOME}/bin/keytool -list -cacerts -storepass changeit -alias "$CA_NAME" | echo $?);
-                if [ "$CA_EXISTS" -eq 0 ];then
-                    ${JAVA_HOME}/bin/keytool -import -trustcacerts -cacerts \
-                        -storepass changeit -noprompt -alias "$CA_NAME" -file $CA_CRT >/dev/null 2>&1 \
-                        | echo "CA Certificates: Added certificate to cacert, $CA_CRT";
-                else 
-                    echo "CA Certificates: Certificate ${CA_NAME} already exists, not adding";
-                fi;
-            done;
-        fi;
+function update_os()
+{
+    get_certs;
+    certs=$(ls /usr/local/share/ca-certificates/*.crt 2> /dev/null | wc -l);
+    if [ "${certs}" -ne 0 ];then
         update-ca-certificates;
     else
-        echo "CA Certificates: Could not find any certificates to import, ensure your certificates have the .crt extension";
+        echo "Cert Updater: No certificates were found to import";
     fi;
+    if [ "${UPDATE}" != "AUTO" ];then
+        cleanup;
+    fi;
+}
+    
+function get_certs()
+{
+    ishttp='^(http|https)';
+    cd /usr/local/share/ca-certificates;
+    if [[ "${URL}" =~ ${ishttp} ]];then
+        wget -r -nH -A ${FILTER} "${URL}";
+    elif [ -d "${URL}" ];then
+        cp -R ${URL}/${FILTER} /usr/local/share/ca-certificates/;
+    else
+        echo "Cert Updater: ${URL} does not exist, nothing to import";
+    fi;
+}
+    
+function cleanup()
+{
+    cd /usr/local/share/ca-certificates;
     rm -rf /usr/local/share/ca-certificates/*;
-else 
-    echo "CA Certificates: Nothing to import, CA_URL is not defined";
+}
+    
+#Run
+while getopts ":hp:c:f:aojk" option; do
+    case $option in
+      h)
+        show_help
+        exit;;
+      p)
+        URL=$OPTARG;;
+      c)
+        SUBJECT=$OPTARG;;
+      f)
+        FILTER=$OPTARG;;
+      a)
+        UPDATE="AUTO";;
+      o)
+        UPDATE="OS";;
+      j)
+        UPDATE="JVM";;
+      k)
+        update_keys
+        exit;;
+      \?)
+        echo "Error: Invalid option, -h for help"
+        exit 2;;
+    esac
+done
+
+if [ "${UPDATE}" == "AUTO" ];then
+    auto_update;
+elif [ "${UPDATE}" == "OS" ];then
+    update_os;
+elif [ "${UPDATE}" == "JVM" ];then
+    update_jvm;
+else
+    echo "Cert Updater: Invalid update type specified";
+    exit 2;
 fi;
+exit 0;
