update to unified runner

diff --git a/src/usr/local/bin/app-config b/src/usr/local/bin/app-config
--- a/src/usr/local/bin/app-config
+++ b/src/usr/local/bin/app-config
@@ -26,12 +26,41 @@ function addCors()
 {
     cp ${APACHE_MODS}/headers_cors_json.conf.dist ${APACHE_MODS}/headers.conf;
 }
+
+function resetConfig()
+{
+    SITE_TEMPLATE=/etc/apache2/sites-available;
+    if [[ -f ${APACHE_MODS}/rewrite.conf ]];then
+        mv -f ${APACHE_MODS}/rewrite.conf ./rewrite.conf.`ls rewrite.conf* | wc -l`;
+    fi;
+    if [[ -f ${APACHE_MODS}/headers.conf ]];then
+        mv -f ${APACHE_MODS}/headers.conf ./headers.conf.`ls headers.conf* | wc -l`;
+    fi;
+    if [[ -f ${APACHE_MODS}/jk.conf ]];then
+        mv -f ${APACHE_MODS}/jk.conf ./jk.conf.`ls jk.conf* | wc -l`;
+    fi;
+    if [[ -f ${APACHE_MODS}/jk.load ]];then
+        mv -f ${APACHE_MODS}/jk.load ./jk.load.`ls jk.load* | wc -l`;
+    fi;
+    if [[ -f ${APACHE_SITES}/000-default.conf ]];then
+        mv -f ${APACHE_SITES}/000-default.conf ./000-default.conf.`ls 000-default.conf* | wc -l`;
+        cp -f ${SITE_TEMPLATE}/000-default.conf.dist ${APACHE_SITES}/000-default.conf;
+    fi;
+    if [[ -f ${APACHE_SITES}/default-ssl.conf ]];then
+        mv -f ${APACHE_SITES}/default-ssl.conf ./default-ssl.conf.`ls default-ssl.conf* | wc -l`;
+        cp -f ${SITE_TEMPLATE}/default-ssl.conf.dist ${APACHE_SITES}/default-ssl.conf;
+    fi;
+}
     
 #Run
     
 echo "App Config: APP_TYPE is ${APP_TYPE}";
     
 APP_RUNAS="www-data";
+    
+if [[ -f /etc/app-init.conf ]];then
+    resetConfig;
+fi;
     
 if [[ "${APP_TYPE}" == "tomcat" ]];then
     APP_RUNAS="tomcat";
@@ -90,9 +119,8 @@ if [[ "${APP_TYPE}" == "apache" ]];then
     if [ -z "$CFG_RESULT" ];then
         echo "App Config: Test FAILED, reverting changes";
         echo "App Config: Result: $CFG_TEST";
-        if [[ -f ${APACHE_MODS}/rewrite.conf ]];then
-            mv ${APACHE_MODS}/rewrite.conf ./rewrite.conf.failed;
-        fi;
+        resetConfig;
+        exit 1;
     else
         echo "App Config: Apache Config Test PASSED, using updated configuration";
         echo "App Config: Apache2 remoteip configured with [address: ${VADC_IP_ADDRESS}, header: ${VADC_IP_HEADER}]";
@@ -104,14 +132,16 @@ if [[ "${APP_TYPE}" == "tomcat" ]];then
     CFG_PASS="INFO: Server initialization in";
     CFG_RESULT=$(echo "$CFG_TEST" | grep "$CFG_PASS");
     if [[ -z $CFG_RESULT ]];then
-        echo "App Config: Tomcat Test FAILED, unrecoverable";
+        echo "App Config: Tomcat Test FAILED, reverting changes";
         echo "App Config: Result: $CFG_TEST";
+        resetConfig;
         exit 1;
     fi;
     echo "App Config: Tomcat RemoteIpValve configured with [internalProxies: ${APP_PROXIES}, remoteIpHeader: ${VADC_IP_HEADER}]";
     echo "App Config: Configured JAVA_OPTS with ${APP_OPTS}";
 fi;
     
+echo "#Container Initialized" > /etc/app-init.conf;
 echo "App Config: Initialization complete"
 echo "App Config: You can use APP_RUNAS variable in your entrypoint to run the app as [ ${APP_RUNAS} ] OR risk it for the biscuit and run as root"; 
     
diff --git a/src/usr/local/bin/app-updater b/src/usr/local/bin/app-updater
--- a/src/usr/local/bin/app-updater
+++ b/src/usr/local/bin/app-updater
@@ -1,6 +1,5 @@
 #!/bin/bash
-############
-    
+
 function get_signature()
 {
     option="$1";
@@ -50,65 +49,66 @@ function update_app()
     
 #Run
     
-if [[ "${APP_TYPE}" == "" ]];then
-    echo "App Updater: Required APP_TYPE is not set, set as apache or tomcat";
-    exit 22;
-elif [[ "${APP_NAME}" == "" ]];then
-    echo "App Updater: Required APP_NAME is not set, use -n to set the name, -h for help";
-    exit 22;
-elif [[ "${APP_UPDATE_PATH}" == "" ]];then
-    echo "App Updater: Required APP_UPDATE_PATH is not set";
-    exit 22;
+if [[ "${APP_UPDATE_PATH}" == "" ]];then
+    echo "App Updater: Required APP_UPDATE_PATH is not set, nothing to do";
 else
-    echo "App Updater: Checking if deployment or update needed";
-fi;
-    
-echo "App Updater: APP_TYPE is ${APP_TYPE}";
-    
-if [[ "${APP_TYPE}" == "apache" ]];then
-    APP_HOME="/var/www/html";
-    APP_DEPLOY="/var/www/html";
-    APP_LATEST="${APP_UPDATE_PATH}/${APP_NAME}";
-fi;
-    
-if [[ "${APP_TYPE}" == "tomcat" ]];then
-    APP_HOME="${CATALINA_HOME}/webapps/";
-    APP_DEPLOY="${APP_HOME}${APP_NAME}.war";
-    APP_LATEST="${APP_UPDATE_PATH}/${APP_NAME}.war";
-    if [[ "${APP_DATA}" == "/var/www/html" ]];then
-        APP_DATA="/etc/${APP_NAME}";
-        echo "App Updater: APP_DATA is set to /var/www, changing to ${APP_DATA}";
+    if [[ "${APP_TYPE}" == "" ]];then
+        echo "App Updater: Required APP_TYPE is not set, set as apache or tomcat";
+        exit 22;
+    elif [[ "${APP_NAME}" == "" ]];then
+        echo "App Updater: Required APP_NAME is not set, use -n to set the name, -h for help";
+        exit 22;
+    else
+        echo "App Updater: Checking if deployment or update needed";
     fi;
-    if [[ "${APP_OWNER}" == "www-data" ]];then
-        APP_OWNER="root";
-        echo "App Updater: APP_OWNER is set to www-data, changing to ${APP_OWNER}";
-    fi;
-    if [[ "${APP_GROUP}" == "www-data" ]];then
-        APP_GROUP="tomcat";
-        echo "App Updater: APP_GROUP is set to www-data, changing to ${APP_GROUP}";
-    fi;
-fi;
     
-if [[ ! -d ${APP_DATA} ]]; then
-    echo "App Updater: Data directory for application does not exist, creating ${APP_DATA}";
-    install -d -m 0770 -o ${APP_OWNER} -g ${APP_GROUP} ${APP_DATA};
-fi
+    echo "App Updater: APP_TYPE is ${APP_TYPE}";
     
-SIG_LOCAL=$(get_signature "local" "${APP_DEPLOY}");
-SIG_UPDATE=$(get_signature "update" "${APP_LATEST}");
-
-if [[ "${SIG_LOCAL}" == "0" ]] && [[ "${SIG_UPDATE}" == "0" ]];then
-    echo "App Updater: Application has not been deployed and was not found in ${APP_UPDATE_PATH}";
-    exit 2;
-elif [[ "${SIG_LOCAL}" == "0" ]] && [[ "${SIG_UPDATE}" != "0" ]];then
-    echo "App Updater: Application has not been deployed, deploying from ${APP_UPDATE_PATH}";
-    deploy_app;
-elif [[ "${SIG_LOCAL}" != "0" ]] && [[ "${SIG_UPDATE}" == "0" ]];then
-    echo "App Updater: Application is deployed but update is empty, failure enabled: ${APP_UPDATE_FAIL}";
-    if [[ "${APP_UPDATE_FAIL}" == 1 ]];then
+    if [[ "${APP_TYPE}" == "apache" ]];then
+        APP_HOME="/var/www/html";
+        APP_DEPLOY="/var/www/html";
+        APP_LATEST="${APP_UPDATE_PATH}/${APP_NAME}";
+    fi;
+    
+    if [[ "${APP_TYPE}" == "tomcat" ]];then
+        APP_HOME="${CATALINA_HOME}/webapps/";
+        APP_DEPLOY="${APP_HOME}${APP_NAME}.war";
+        APP_LATEST="${APP_UPDATE_PATH}/${APP_NAME}.war";
+        if [[ "${APP_DATA}" == "/var/www/html" ]];then
+            APP_DATA="/etc/${APP_NAME}";
+            echo "App Updater: APP_DATA is set to /var/www, changing to ${APP_DATA}";
+        fi;
+        if [[ "${APP_OWNER}" == "www-data" ]];then
+            APP_OWNER="root";
+            echo "App Updater: APP_OWNER is set to www-data, changing to ${APP_OWNER}";
+        fi;
+        if [[ "${APP_GROUP}" == "www-data" ]];then
+            APP_GROUP="tomcat";
+            echo "App Updater: APP_GROUP is set to www-data, changing to ${APP_GROUP}";
+        fi;
+    fi;
+    
+    if [[ ! -d ${APP_DATA} ]]; then
+        echo "App Updater: Data directory for application does not exist, creating ${APP_DATA}";
+        install -d -m 0770 -o ${APP_OWNER} -g ${APP_GROUP} ${APP_DATA};
+    fi
+    
+    SIG_LOCAL=$(get_signature "local" "${APP_DEPLOY}");
+    SIG_UPDATE=$(get_signature "update" "${APP_LATEST}");
+    
+    if [[ "${SIG_LOCAL}" == "0" ]] && [[ "${SIG_UPDATE}" == "0" ]];then
+        echo "App Updater: Application has not been deployed and was not found in ${APP_UPDATE_PATH}";
         exit 2;
+    elif [[ "${SIG_LOCAL}" == "0" ]] && [[ "${SIG_UPDATE}" != "0" ]];then
+        echo "App Updater: Application has not been deployed, deploying from ${APP_UPDATE_PATH}";
+        deploy_app;
+    elif [[ "${SIG_LOCAL}" != "0" ]] && [[ "${SIG_UPDATE}" == "0" ]];then
+        echo "App Updater: Application is deployed but update is empty, failure enabled: ${APP_UPDATE_FAIL}";
+        if [[ "${APP_UPDATE_FAIL}" == 1 ]];then
+            exit 2;
+        fi;
+    else
+        echo "App Updater: Auto-update is enabled: ${APP_UPDATE_AUTO}, deployed: ${SIG_LOCAL}, latest: ${SIG_UPDATE}";
+        update_app;
     fi;
-else
-    echo "App Updater: Auto-update is enabled: ${APP_UPDATE_AUTO}, deployed: ${SIG_LOCAL}, latest: ${SIG_UPDATE}";
-    update_app;
 fi;
